object: build/DEBUG/orig/ratsgc_d.dol
hash: 7f88dc05c525fa9f7a0b5b5dc1233a27239dea99
symbols: config/DEBUG/symbols.txt
splits: config/DEBUG/splits.txt
symbols_known: true
fill_gaps: false
ldscript_template: config/DEBUG/ldscript.tpl

block_relocations:
- target: 0x80808040
- target: 0x80808080
- target: 0x80808081
- target: 0x808080FF
- target: 0x80CC99FF