#ifndef ZMINIGAMETYPES_H
#define ZMINIGAMETYPES_H

#include "types.h"

enum ezMiniGameTypes
{
    MG_GAMETYPE_UNKNOWN,
    MG_GAMETYPE_TYPE1,
    MG_GAMETYPE_DEFENDTHEBASE,
    MG_GAMETYPE_RATONBALL,
    MG_GAMETYPE_PUFFEROIDS,
    MG_GAMETYPE_GRAPESTOMPER,
    MG_GAMETYPE_CONGALINE,
    MG_GAMETYPE_AVOIDTHESTUFF,
    MG_GAMETYPE_COUNT
};

#endif
