object: build/RELEASE/orig/ratsgc_r.dol
hash: d8b8e9f889a1362105c49144ff39a234d58386b9
symbols: config/RELEASE/symbols.txt
splits: config/RELEASE/splits.txt
symbols_known: true
fill_gaps: false
ldscript_template: config/RELEASE/ldscript.tpl

block_relocations:
- target: 0x80808040
- target: 0x80808080
- target: 0x80808081
- target: 0x808080FF