object: build/MASTER/orig/ratsgc_m.dol
hash: 674613ef86a955fa6a661d027e80adaf192b24f2
symbols: config/MASTER/symbols.txt
splits: config/MASTER/splits.txt
symbols_known: true
fill_gaps: false
ldscript_template: config/MASTER/ldscript.tpl

block_relocations:
- target: 0x803C3E1C
